# Generated by Django 4.1.7 on 2023-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_type',
            field=models.IntegerField(choices=[(1, 'Google')], default=None, null=True),
        ),
    ]
