# Generated by Django 4.1.7 on 2023-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_oauth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
